export const LanguageZh = {
	"auto": "自动检测",
	"zh_cn": "简体中文",
	"zh_tw": "繁體中文",
	"ja": "日语",
	"en": "英语",
	"ko": "韩语",
	"fr": "法语",
	"es": "西班牙语",
	"ru": "俄语",
	"de": "德语",
	"it": "意大利语",
	"tr": "土耳其语",
	"pt_pt": "葡萄牙语",
	"pt_br": "葡萄牙语 (巴西)",
	"vi": "越南语",
	"id": "印尼语",
	"th": "泰语",
	"ms": "马来语",
	"ar": "阿拉伯语",
	"hi": "印地语",
	"mn_mo": "蒙古语",
	"mn_cy": "蒙古语(西里尔)",
	"km": "高棉语",
	"nb_no": "书面挪威语",
	"nn_no": "新挪威语",
	"fa": "波斯语",
	"sv": "瑞典语",
	"pl": "波兰语",
	"nl": "荷兰语"
}

export const LanguageList = Object.keys(LanguageZh)